In [2]:
import numpy as np

In [3]:
np.char.center('Hello', 20, fillchar='-')

array('-------Hello--------', dtype='<U20')

In [4]:
np.char.center('Hello', 3)

array('Hel', dtype='<U3')

In [5]:
np.char.capitalize('hello, World!')

array('Hello, world!', dtype='<U13')

In [6]:
np.char.title('how are you doing?')  # capitalize each word

array('How Are You Doing?', dtype='<U18')

In [7]:
np.char.lower('MOTHER')

array('mother', dtype='<U6')

In [8]:
np.char.lower(['FATHER', 'SON'])

array(['father', 'son'], dtype='<U6')

In [10]:
np.char.split('hello mother how are you')

array(list(['hello', 'mother', 'how', 'are', 'you']), dtype=object)

In [11]:
np.char.splitlines('hello\ndear\nfriend!')

array(list(['hello', 'dear', 'friend!']), dtype=object)

In [15]:
np.char.strip(['Sasha', 'do you like to eat', 'apples?'], 'a')
# can't understand behavior of the function .strip()

array(['Sash', 'do you like to eat', 'pples?'], dtype='<U18')

In [20]:
np.char.join(['+', '*', '-'], ['I', 'like', 'monkeys!'])  # many separators

array(['I', 'l*i*k*e', 'm-o-n-k-e-y-s-!'], dtype='<U15')

In [22]:
np.char.join(['+'], ['I like monkeys!'])  # one separator

array(['I+ +l+i+k+e+ +m+o+n+k+e+y+s+!'], dtype='<U29')

In [25]:
np.char.join(['-', ':'], [['21', '01', '2023'], ['19', '30']])

C:\Python310\lib\site-packages\numpy\core\defchararray.py:960: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  _vec_string(sep, object_, 'join', (seq,)))


array(['21-01-2023', '19:30'], dtype='<U10')

In [26]:
np.char.replace('I am a good economist!', 'am', 'was')

array('I was a good economist!', dtype='<U23')

In [27]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
b = a.reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
b.flatten(order='F')  # return matrix in one dimension array

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [35]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [38]:
print(np.transpose(a))  # print shows matrix without array

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [40]:
b = np.arange(8).reshape(2, 4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
c = b.reshape(2, 2, 2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
np.rollaxis(c, 1)
#  https://numpy.org/doc/stable/reference/generated/numpy.rollaxis.html

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [48]:
np.rollaxis(c, 2)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [46]:
np.rollaxis(c, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [52]:
np.swapaxes(c, 1, 2)
#  https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])