In [1]:
import numpy as np

In [3]:
import time
import sys

In [4]:
b = range(1000)
sys.getsizeof(b)

48

In [11]:
sys.getsizeof(b)  # how much iterator used mamory

48

In [9]:
c = np.arange(1000)

In [10]:
sys.getsizeof(c)  # hom much mamory use numpy array

4104

In [12]:
print(sys.getsizeof(tuple(b)))
print(sys.getsizeof(list(b)))  # list uses not much more mamory then tuple

8040
8056


In [14]:
print(c.size)
print(c.itemsize)

1000
4


In [16]:
size = 100_000
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [17]:
start = time.time()
result = [(x + y) for x, y in zip(L1, L2)]
print(f'python list took {1000 * (time.time() - 1000)}')

python list took 1673020571321.4844


In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [19]:
a.ndim  # quantity of dimensions

2

In [24]:
a.itemsize  # return the length of one array element in bytes

4

In [25]:
a.shape

(3, 2)

In [26]:
b = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
b.itemsize

8

In [28]:
c = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.complex)
print(c)
print(c.itemsize)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]
16


C:\Users\ultra\AppData\Local\Temp\ipykernel_2368\258823430.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.complex)


In [29]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.char.add(['hello ', 'good '], ['World!', 'bye'])  # concatination function

array(['hello World!', 'good bye'], dtype='<U12')

In [33]:
np.char.multiply('Sasha ', 3)

array('Sasha Sasha Sasha ', dtype='<U18')