# Numpy atithmetic operations

In [1]:
import numpy as np

In [3]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b = np.array([10, 10, 10])
b

array([10, 10, 10])

In [5]:
np.add(a, b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
np.subtract(a, b)  # each row in a subtract [10, 10, 10]

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [8]:
np.multiply(a, b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [9]:
np.divide(a, b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

## slicing

In [11]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
a[:4]

array([0, 1, 2, 3])

In [14]:
a[5]

5

In [16]:
s = slice(2, 9, 2)  # value in index
a[s]

array([2, 4, 6, 8])

## iterating over array

In [17]:
a = np.arange(0, 45, 5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [19]:
a = a.reshape(3, 3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [20]:
for x in np.nditer(a):  # nditer(array) - fastest iterator
    print(x)

0
5
10
15
20
25
30
35
40


In [22]:
# C-style of iteration came from C language
# F-style of iteration came from Fortran language
print(a)
for x in np.nditer(a, order='C'):
    print(x)
    
print()    
for x in np.nditer(a, order='F'):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40

0
15
30
5
20
35
10
25
40


## joining arrays

In [28]:
a = np.array([[1, 2], [3, 4]])
print(f'first array')
print(a)
print()

b = np.array([[5, 6], [7, 8]])
print(f'second array')
print(b)

np.concatenate((a, b))  # column vector, add new rows

first array
[[1 2]
 [3 4]]

second array
[[5 6]
 [7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
np.concatenate((a, b), axis=1)  # row vector, add new columns

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## splitting array

In [31]:
a = np.arange(9)
print(a)
np.split(a, 3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [33]:
np.split(a, [4, 6])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]

## resizing an array

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a.shape

(2, 3)

In [39]:
b = np.resize(a, (3, 2))
b  # resize is good to make new array by changing existing one

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
c = np.resize(a, (3, 3))  # dublicated first row of a
c

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])